export default {
  SET_HEAD_NAVIGATOR: 'SET_HEAD_NAVIGATOR',
  PLAY_VIDEO: 'PLAY_VIDEO',
  RESET_VIDEO: 'RESET_VIDEO',
  PRESSED: 'PRESSED',
  FULLSCREEN: 'FULLSCREEN',
  // RESET_VIDEO : 'RESET_VIDEO',
};
